del /s /q *._2i
del /s /q *.__i
del /s /q *.build_log.htm
del /s /q *.crf
del /s /q *.d
del /s /q *.dep
del /s /q *.fed
del /s /q *.l2p
del /s /q *.lnp
del /s /q *.lo
del /s /q *.log
del /s /q *.map
del /s /q *.o
del /s /q *.obj
del /s /q *.slo
del /s /q *.uvgui.*
del /s /q *.uvguix.*
del /s /q JLinkLog.txt
@pause
